apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-app-deployment
  labels:
    app: will
  namespace: dev
spec:
  replicas: 7
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
      - name: will
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
